import type { XIAOBoard } from '../types.js';

export const nrf54l15: XIAOBoard = {
  id: 'nrf54l15',
  name: 'XIAO nRF54L15',
  fullName: 'Seeed Studio XIAO nRF54L15',
  microcontroller: 'Nordic nRF54L15',
  architecture: 'Dual-core (Arm Cortex-M33 + RISC-V)',
  clockSpeed: '128 MHz',
  flashSize: '1.5MB',
  ramSize: '256KB',
  onboardFlash: 'N/A',
  pins: {
    digital: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    analog: [0, 1, 2, 3],
    pwm: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    i2c: [{ sda: 6, scl: 7 }],
    spi: [{ mosi: 9, miso: 8, sck: 10, cs: 3 }],
    uart: [{ tx: 0, rx: 1 }],
  },
  features: ['USB-C', 'Battery charging', 'User LED'],
  connectivity: ['Bluetooth 6.0', 'Matter', 'Zigbee'],
  builtinSensors: [],
  supportedLanguages: ['platformio', 'zephyr'],
  lowPowerMode: 'N/A',
  hasResetButton: true,
  hasBootButton: true,
  hasBatteryCharging: true,
  wikiUrl: 'https://wiki.seeedstudio.com/xiao_nrf54l15_sense_getting_started/',
  sku: '101991421',
};

export const nrf54l15Sense: XIAOBoard = {
  id: 'nrf54l15-sense',
  name: 'XIAO nRF54L15 Sense',
  fullName: 'Seeed Studio XIAO nRF54L15 Sense',
  microcontroller: 'Nordic nRF54L15',
  architecture: 'Dual-core (Arm Cortex-M33 + RISC-V)',
  clockSpeed: '128 MHz',
  flashSize: '1.5MB',
  ramSize: '256KB',
  onboardFlash: 'N/A',
  pins: {
    digital: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    analog: [0, 1, 2, 3],
    pwm: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    i2c: [{ sda: 6, scl: 7 }],
    spi: [{ mosi: 9, miso: 8, sck: 10, cs: 3 }],
    uart: [{ tx: 0, rx: 1 }],
  },
  features: ['USB-C', 'Battery charging', 'User LED'],
  connectivity: ['Bluetooth 6.0', 'Matter', 'Zigbee'],
  builtinSensors: ['6-axis IMU', 'Microphone'],
  supportedLanguages: ['platformio', 'zephyr'],
  lowPowerMode: 'N/A',
  hasResetButton: true,
  hasBootButton: true,
  hasBatteryCharging: true,
  wikiUrl: 'https://wiki.seeedstudio.com/xiao_nrf54l15_sense_getting_started/',
  sku: '101991422',
};
